<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Mon, 27 May 2019 23:34:02 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
